name: MapleMono-NF-CN-unhinted.zip
link: https://github.com/subframe7536/maple-font/releases/download/v7.4/MapleMono-NF-CN-unhinted.zip
hash: sha256:9b439e9c48a77ea3b314f77d27ef61be6956672a3d80de3c2acbed9d22596d0c
includeArchiveEntries:
  - "*-Bold.ttf"
  - "*-Medium.ttf"
  - "*-Regular.ttf"