ktor {
    development = true
    deployment {
        port = 8888
        watch = [ classes, resources ]
    }
    application {
        modules = [ com.storyteller_f.a.app.dev_server.DevServerApplicationKt.module ]
    }
}