services:
  dev:
    build:
      context: ../
      dockerfile: ./dev.Dockerfile
      args:
        - OPENJDK_VERSION=21
    ports:
      - "6081:6080" # noVNC web interface
      - "5902:5901" # VNC direct connection
      - "5556:5555" # ADB
      - "4724:4723" # Appium
    environment:
      - VNC_PASSWD=password
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    volumes:
      - ..:/workspace/A:cached
      - avd_data:/root/.android/avd
      - sdk_data:/opt/android/sdk
      - gradle_data:/root/.gradle
      - konan_data:/root/.konan
      - /var/run/docker.sock:/var/run/docker.sock  # 宿主机 Docker 套接字
    shm_size: '2gb' # Allocate more shared memory
    privileged: true # Enable KVM acceleration

volumes:
  avd_data:
  sdk_data:
    name: sdk_data
    external: true
  gradle_data:
    name: gradle_data
    external: true
  konan_data:
    name: konan_data
    external: true
