ktor {
    development = true
    deployment {
        port = 8813
        watch = [ classes, resources ]
    }
    application {
        modules = [ com.storyteller_f.a.cloud.ws.WsApplicationKt.module ]
    }
}
