services:
  server:
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy

  prebuild-server:
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy