services:
  server:
    deploy:
      resources:
        limits:
          #memory: 200M         # 最大内存限制为 200MB
          cpus: "0.5"          # 限制使用最多 50% 的 CPU 核心
        #reservations:
          #memory: 100M         # 软内存限制为 100MB