FROM openjdk:17-jdk AS builder

RUN microdnf install findutils

WORKDIR /app

COPY . .

RUN sed -i 's/\r$//' scripts/build-server.sh
RUN sed -i 's/\r$//' gradlew

RUN sh scripts/build-server.sh

FROM koyeb/docker-compose

WORKDIR /app

COPY --from=builder /app/server/build/libs/*-all.jar .

COPY . .