services:
  main:
    build:
      context: ../
      dockerfile: ./dev.Dockerfile
      args:
        - OPENJDK_VERSION=21
    ports:
      - "6081:6080" # noVNC web interface
      - "5902:5901" # VNC direct connection
      - "5556:5555" # ADB
      - "4724:4723" # Appium
    environment:
      - VNC_PASSWD=password
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    volumes:
      - ..:/workspace/A:cached
      - ../../AData:/workspace/AData
      - avd_data:/root/.android/avd
      - sdk_data:/opt/android/sdk
      - a-bashhistory:/commandhistory
      - ~/.gradle:/root/.gradle
      - ~/.konan:/root/.konan
      - ~/.m2:/root/.m2
      - /var/run/docker.sock:/var/run/docker.sock  # 宿主机 Docker 套接字
    shm_size: '2gb' # Allocate more shared memory
    privileged: true # Enable KVM acceleration

volumes:
  avd_data:
  a-bashhistory:
  sdk_data:
    name: sdk_data
    external: true
