services:
  server:
    build:
      context: ../../
      args:
        BUILD_TYPE: ${BUILD_TYPE}
        FLAVOR: ${FLAVOR}
        BUILD_ON: ${BUILD_ON}
#    restart: unless-stopped
    env_file:
      - ../../deploy/${FLAVOR}.env
    ports:
      - ${SERVER_EXPOSE_PORT}:${SERVER_PORT}
    volumes:
      - ${PRESET_PATH}:/app/deploy/preset_data
