services:
  worker:
    build:
      context: ../../
      dockerfile: worker.Dockerfile
      args:
        BUILD_TYPE: ${BUILD_TYPE}
        FLAVOR: ${FLAVOR}
    restart: unless-stopped
    env_file:
      - ../../deploy/${FLAVOR}.env
