services:
  worker:
    build:
      context: ../../
      dockerfile: worker.Dockerfile
      args:
        BUILD_TYPE: ${BUILD_TYPE}
        FLAVOR: ${FLAVOR}
    env_file:
      - ../../${FLAVOR}.env
