volumes:
  pg-data:

services:
  pg:
    image: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      PGOPTIONS: --statement_timeout=5000
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DATABASE_DB} -U ${DATABASE_USER}" ]
      interval: 1s
      start_period: 5s
    volumes:
      - pg-data:/var/lib/postgresql/data
    profiles:
      - pg

  adminer:
    image: adminer
    ports:
      - ${DATABASE_FRONT_PORT}:8080
    depends_on:
      pg:
        condition: service_healthy
    profiles:
      - pg
  exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_URI: "localhost:5432/postgres?sslmode=disable"
      DATA_SOURCE_USER: ${DATABASE_USER}
      DATA_SOURCE_PASS: ${DATABASE_PASS}
    profiles:
      - pg