name: Android CI

on:
  push:
    branches: [ "alpha" ]
    paths:
      - 'composeApp/**'
      - 'shared/**'
      - 'scripts/build_scripts/build-app-on-ci.sh'
      - 'scripts/tool_scripts/modify-flavor.sh'
      - 'gradle/**'
      - 'crypto-jvm/**'
      - 'client-lib/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Build mini app
        run: ./scripts/build_scripts/build-app-on-ci.sh https://acommunity.link/ mini

      - name: Build koyeb app
        run: ./scripts/build_scripts/build-app-on-ci.sh https://respectable-jobie-anabn-3d54150c.koyeb.app/server/ koyeb

      - uses: actions/upload-artifact@v4
        with:
          name: Signed A Bundle
          path: build/outputs/apk/release/
