name: Android CI

on:
  push:
    branches: [ "alpha" ]

jobs:
  build:
    environment: koyeb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Build app
        run: sh scripts/build_scripts/build-service-on-ci.sh

      - uses: actions/upload-artifact@v4
        with:
          name: Signed app bundle
          path: build/outputs/apk/release/
