name: Android CI

on:
  push:
    branches: [ "alpha" ]
    paths:
      - '.github/workflows/alpha.yml'
      - 'composeApp/**'
      - 'shared/**'
      - 'scripts/build_scripts/build-app-on-ci.sh'
      - 'scripts/tool_scripts/modify-flavor.sh'
      - 'gradle/**'
      - 'crypto-jvm/**'
      - 'client-lib/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # this will take the entire vars context configured in the repository > environments
      # setting and convert it to JSON so we can automatically assign all the values to the
      # runner's environment
      VARS_CONTEXT: ${{ toJson(vars) }}
      SECRETS_CONTEXT: ${{ toJson(secrets) }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Build mini app
        run: ./scripts/build_scripts/build-app-on-ci.sh mini www.acommunity.link android

      - name: Build koyeb app
        run: ./scripts/build_scripts/build-app-on-ci.sh koyeb respectable-jobie-anabn-3d54150c.koyeb.app/server/ android

      - name: Build mini deb
        run: ./scripts/build_scripts/build-app-on-ci.sh mini www.acommunity.link desktop-deb

      - name: Build koyeb deb
        run: ./scripts/build_scripts/build-app-on-ci.sh koyeb respectable-jobie-anabn-3d54150c.koyeb.app/server/ desktop-deb

      - uses: actions/upload-artifact@v4
        with:
          name: Signed A Bundle
          path: |
            build/outputs/apk/release/
            build/outputs/pkg/release/
  build-desktop-msi:
    runs-on: windows-latest
    env:
      # this will take the entire vars context configured in the repository > environments
      # setting and convert it to JSON so we can automatically assign all the values to the
      # runner's environment
      VARS_CONTEXT: ${{ toJson(vars) }}
      SECRETS_CONTEXT: ${{ toJson(secrets) }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Build mini msi
        run: "C:\\Program Files\\Git\\bin\\bash.exe" -c "./scripts/build_scripts/build-app-on-ci.sh mini www.acommunity.link desktop-msi"

      - name: Build koyeb msi
        run: "C:\\Program Files\\Git\bin\\bash.exe" -c "./scripts/build_scripts/build-app-on-ci.sh koyeb respectable-jobie-anabn-3d54150c.koyeb.app/server/ desktop-msi"

      - uses: actions/upload-artifact@v4
        with:
          name: Signed A Bundle
          path: |
            build/outputs/pkg/release/