name: Alpha Server CI

on:
  workflow_dispatch:
  push:
    branches: [ "alpha" ]
    paths:
      - '.github/workflows/alpha-server.yml'
      - 'backend/**'
      - 'cli/**'
      - 'api/**'
      - 'scripts/**'
      - 'cloud/**'
      - 'bgscripts/**'
      - 'shared/**'
      - 'gradle/**'
      - '*.kts'
      - 'Dockerfile'
      - 'docker-image-in-test'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: alpha
    env:
      # this will take the entire vars context configured in the repository > environments
      # setting and convert it to JSON so we can automatically assign all the values to the
      # runner's environment
      VARS_CONTEXT: ${{ toJson(vars) }}
      SECRETS_CONTEXT: ${{ toJson(secrets) }}
      ORG_GRADLE_PROJECT_gpr_user: ${{ github.actor }}
      ORG_GRADLE_PROJECT_gpr_key: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Update Docker images used in tests
        run: ./scripts/docker_image_scripts/update-docker-image-in-test.sh
      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('Dockerfile', 'docker-image-in-test', 'scripts/docker_image_scripts/update-docker-image-in-test.sh') }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run backend tests
        run: ENABLE_TEST_CONTAINER=true ./gradlew :backend:minio:test :cloud:cli:test :cloud:service:test :cloud:server:test --console=plain
      - name: Start service
        run: ./scripts/service_scripts/start-service-on-ci.sh alpha
