name: Android CI

on:
  push:
    branches: [ "alpha" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Prepare env
        run: |
          chmod +x scripts/generate-mini-env-for-app.sh
          ./scripts/generate-mini-env-for-app.sh https://respectable-jobie-anabn-3d54150c.koyeb.app

      - name: Build app
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Rename
        run: mv composeApp/build/outputs/apk/release/*.apk composeApp/build/outputs/apk/release/A-release.apk

      - uses: actions/upload-artifact@v4
        with:
          name: Signed app bundle
          path: composeApp/build/outputs/apk/release/A-release.apk
